# Generated by Django 3.0.1 on 2020-01-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='parent_article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Comment', verbose_name='Parent comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_icon',
            field=models.ImageField(default='https://friconix.com/jpg/fi-cwluxl-question-mark.jpg', upload_to='user_icons/', verbose_name='User icon'),
        ),
    ]
