# Generated by Django 3.0.1 on 2020-01-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200107_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_icon',
            field=models.ImageField(default='defaults/unknown.png', upload_to='user_icons/', verbose_name='User icon'),
        ),
    ]
