# Generated by Django 3.0.1 on 2020-07-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200107_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='number_of_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
